### ISSUE TITLE
Startpage missing if no project is followed

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/project-manager#9]
Currently, the manager works if there are any projects to follow (entries in the respective following table are present).

We need to treat the case properly, if currently no project is followed.

**Comment by sven1103** [comment]
12:16:24,367 INFO  [ManagerUI:76] Started project-manager.
12:16:24,368 INFO  [ManagerUI:81] UserID = bbbfs01
12:16:24,368 INFO  [ManagerUI:108] Connection to SQL project database was successful.
Could not connect to target SQL database. Reason: Illegal operation on empty result set.
java.sql.SQLException: Illegal operation on empty result set.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
        at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:815)
        at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5528)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5448)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5488)
        at life.qbic.projectFollowerModule.ProjectFollowerModel.loadFollowingProjects(ProjectFollowerModel.java:61)
        at life.qbic.projectFollowerModule.ProjectFollowerPresenter.startOrchestration(ProjectFollowerPresenter.java:45)
        at life.qbic.ManagerUI.init(ManagerUI.java:136)

**Comment by sven1103** [comment]
I get this when trying to load the project-manager on portal-testing

**Comment by julianspaeth** [comment]
Because there are no followed projects in the set? Or due to another reason?

**Comment by sven1103** [comment]
no projects followed. So if you aren't following any project, the SQL Query is empty and thus no rows can be visualized.

**Comment by sven1103** [comment]
My Suggestion: Implement an alternative view, that gets visualised, when there are currently no projects followed. Otherwise show the grid.

**Comment by julianspaeth** [comment]
Does it just affect the grid or also the chart? Good idea, i will implement it as you suggested.

**Comment by sven1103** [comment]
i think only the grid

**Comment by sven1103** [comment]
but that is easy to test ;)
